name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Use Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
          version: nightly

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci

    - name: Clean
      run: make clean

    - name: Remove lib
      run: make remove

    - name: Install dependencies
      run: make install  

    - name: Compile contracts
      run: make build

    - name: Run Tests
      run: make test

    - name: Run Snapshots
      run: make snapshot