name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure
    - name: Clean
      run: make clean
    - name: Remove lib
      run: make remove
    - name: Install dependencies
      run: make install    
    - name: Update dependencies
      run: make update
    - name: Compile contracts
      run: make build
    - name: Run Tests
      run: make test
