name: Node.js Package

on:
    release:
        types: [created]

jobs:
    build:
        uses: paymasters-io/contracts/.github/workflows/test.yml@main
    spell-check:
        uses: paymasters-io/contracts/.github/workflows/spell-check.yml@main
    analyze:
        uses: paymasters-io/contracts/.github/workflows/slither.yml@main

    publish:
        needs: [build, spell-check, analyze]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
