name: Slither Analysis

on: [push, pull_request, workflow_call]

jobs:
    build:
        uses: paymasters-io/contracts/.github/workflows/test.yml@main
    analyze:
        needs: [build]
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
            - uses: actions/checkout@v3

            - name: Run Slither
              uses: crytic/slither-action@v0.3.0
              id: slither
              with:
                  sarif: results.sarif
                  fail-on: none

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: ${{ steps.slither.outputs.sarif }}
